const viewProductData = [
    {
        id: 1,
        productName: "sam 1",
        productCode: "Product 1",
        productSize: "1",
        productQuantity: "1",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 2,
        productName: "sam 2",
        productCode: "Product 2",
        productSize: "2",
        productQuantity: "2",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 3,
        productName: "sam 3",
        productCode: "Product 3",
        productSize: "3",
        productQuantity: "3",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 4,
        productName: "sam 4",
        productCode: "Product 4",
        productSize: "4",
        productQuantity: "4",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 5,
        productName: "sam 5",
        productCode: "Product 5",
        productSize: "5",
        productQuantity: "5",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 6,
        productName: "sam 6",
        productCode: "Product 6",
        productSize: "6",
        productQuantity: "6",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 7,
        productName: "sam 7",
        productCode: "Product 7",
        productSize: "7",
        productQuantity: "7",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 8,
        productName: "sam 8",
        productCode: "Product 8",
        productSize: "8",
        productQuantity: "8",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 9,
        productName: "sam 9",
        productCode: "Product 9",
        productSize: "9",
        productQuantity: "9",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
    {
        id: 10,
        productName: "sam 10",
        productCode: "Product 10",
        productSize: "10",
        productQuantity: "10",
        productRate: "1",
        productCompanyName: "xyz",
        price: 0,
        addItem: `<input type="checkbox" class="check-box">`,
        editBtn: `<button class="edit-btn btn">Edit</button>`,
        deleteBtn: `<button class="delete-btn btn">Delete</button>`,
        address: "india",
        number: 1234532343,
    },
 
];
export default viewProductData;
